baseURL = "https://zhyg.github.io"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
title = "Yangong's Blog"

hasCJKLanguage = true
theme = "LoveIt"
paginate = 10
enableEmoji = true
enableRobotsTXT = true

publishDir = "docs"

[Permalinks]
# posts = ":year/:month/:filename"
  posts = ":filename/"

[author]
  name = "yangong"

[menu]
  [[menu.main]]
    name = "文档"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "幻灯片"
    url = "/categories/slide/"
    weight = 4
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 5

# 主题配置参考：https://hugoloveit.com/zh-cn/theme-documentation-basics/
[params]
  # LoveIt 主题版本
  version = "0.1.X"
  # 网站描述
  description = "yangong 的博客"
  # 网站关键词
  keywords = ["RD"]
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "auto"

  # 页面头部导航栏信息
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"

  # 页面底部版权信息设置
  [params.footer]
    # 网站创立年份
    since = 2019
    # 许可协议信息 (允许使用 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.home]
    # 主页信息设置
    [params.home.profile]
      enable = true
      # 主页显示头像的 URL
      avatarURL = "/images/me.jpeg"
      # 主页显示的网站副标题
      subtitle = "开心的活着"
      # 是否为副标题显示打字机动画
      typeit = true
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

     # 文章页面配置
  [params.page]
    # 是否在文章页面使用 lightgallery
    lightgallery = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
  # 数学公式 (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # 默认内联定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX 插件 mhchem
    mhchem = true

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

